Error: "Media is null." Commented out  media in function.
Content is showing when media is commented out, but not showing when media-content is in the function.

Reason might be that some of the posts are missing an img. and then nothing will show. Maybe add a function that displayes a placeholder img. on post that have no img.